version: '3'
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_USER=guacamole_user
      - POSTGRES_PASSWORD=guacamole_password
    depends_on:
      - guacd
      - postgres
    ports:
      - "8080:8080"
  guacd:
    image: oznu/guacd
    container_name: guacd
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=guacamole_user
      - POSTGRES_PASSWORD=guacamole_password
      - POSTGRES_DB=guacamole_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
